/**
 * Comic Cons & Collectible Events Data
 * Compiled from: comicconventionlist.com, upcomingcons.com, conventionscene.com, thepopverse.com
 * 
 * Tier 1: Massive / National Draw (the "NFL franchises" of comic cons)
 * Tier 2: Major Regional Conventions
 * Tier 3: Strong Regional / Niche / Growing
 * Tier 4: Local / Recurring / Smaller Shows
 */

export interface ComicConEvent {
  name: string;
  city: string;
  state: string;
  stateAbbr: string;
  dates: string;
  startDate: string; // YYYY-MM-DD for sorting
  endDate: string;
  tier: 1 | 2 | 3 | 4;
  type: "comic-con" | "collectibles" | "anime-gaming" | "pop-culture" | "card-show";
  description: string;
  website?: string;
  recurring?: boolean;
  highlights?: string[];
}

export const comicConEvents: ComicConEvent[] = [
  // ===== TIER 1: MASSIVE / NATIONAL DRAW =====
  {
    name: "Comic-Con International: San Diego (SDCC)",
    city: "San Diego",
    state: "California",
    stateAbbr: "CA",
    dates: "July 22–26, 2026",
    startDate: "2026-07-22",
    endDate: "2026-07-26",
    tier: 1,
    type: "comic-con",
    description: "The biggest comic convention in the world. 130,000+ attendees, massive Hall H panels, exclusive collectibles, and the epicenter of pop culture announcements. If you're serious about comics and collectibles, this is the Super Bowl.",
    website: "https://www.comic-con.org",
    highlights: ["Hall H panels", "Exclusive collectibles", "Artist Alley", "Cosplay", "Movie/TV premieres"],
  },
  {
    name: "New York Comic Con (NYCC)",
    city: "New York City",
    state: "New York",
    stateAbbr: "NY",
    dates: "October 8–11, 2026",
    startDate: "2026-10-08",
    endDate: "2026-10-11",
    tier: 1,
    type: "comic-con",
    description: "The East Coast's biggest pop culture event at the Javits Center. 200,000+ attendees across 4 days. Major publisher panels, celebrity guests, and one of the largest show floors in the country for comics, toys, and collectibles.",
    website: "https://www.newyorkcomiccon.com",
    highlights: ["Javits Center", "Publisher panels", "Artist Alley", "Funko exclusives", "Anime content"],
  },
  {
    name: "C2E2 (Chicago Comic & Entertainment Expo)",
    city: "Chicago",
    state: "Illinois",
    stateAbbr: "IL",
    dates: "March 27–29, 2026",
    startDate: "2026-03-27",
    endDate: "2026-03-29",
    tier: 1,
    type: "comic-con",
    description: "Chicago's premier pop culture convention at McCormick Place. One of the top 5 cons in the US with major comic publishers, celebrity guests, incredible cosplay, and a massive show floor packed with dealers and artists.",
    website: "https://www.c2e2.com",
    highlights: ["McCormick Place", "Crown Championships of Cosplay", "Comic publishers", "Gaming area"],
  },
  {
    name: "MegaCon Orlando",
    city: "Orlando",
    state: "Florida",
    stateAbbr: "FL",
    dates: "March 19–22, 2026",
    startDate: "2026-03-19",
    endDate: "2026-03-22",
    tier: 1,
    type: "comic-con",
    description: "The Southeast's largest comic, sci-fi, horror, anime, and gaming event. 100,000+ fans descend on the Orange County Convention Center for 4 days of celebrity guests, artist alley, cosplay contests, and massive vendor halls.",
    website: "https://www.megaconvention.com",
    highlights: ["Orange County Convention Center", "Celebrity photo ops", "Cosplay contest", "Kids activities"],
  },
  {
    name: "Emerald City Comic Con (ECCC)",
    city: "Seattle",
    state: "Washington",
    stateAbbr: "WA",
    dates: "March 5–8, 2026",
    startDate: "2026-03-05",
    endDate: "2026-03-08",
    tier: 1,
    type: "comic-con",
    description: "The Pacific Northwest's biggest convention and one of the top 5 in the US. Known for its strong indie comics scene, incredible artist alley, and passionate community. Held at the Washington State Convention Center.",
    website: "https://www.emeraldcitycomiccon.com",
    highlights: ["Artist Alley", "Indie comics focus", "Cosplay", "Panels"],
  },
  {
    name: "WonderCon",
    city: "Anaheim",
    state: "California",
    stateAbbr: "CA",
    dates: "March 27–29, 2026",
    startDate: "2026-03-27",
    endDate: "2026-03-29",
    tier: 1,
    type: "comic-con",
    description: "SDCC's 'little sibling' — but still massive. Held at the Anaheim Convention Center, WonderCon draws 60,000+ fans with major publisher panels, celebrity guests, and a more intimate feel than San Diego. Great for families.",
    website: "https://www.comic-con.org/wca",
    highlights: ["Anaheim Convention Center", "DC/Marvel panels", "Masquerade", "Family-friendly"],
  },

  // ===== TIER 2: MAJOR REGIONAL =====
  {
    name: "Dragon Con",
    city: "Atlanta",
    state: "Georgia",
    stateAbbr: "GA",
    dates: "September 3–7, 2026",
    startDate: "2026-09-03",
    endDate: "2026-09-07",
    tier: 2,
    type: "pop-culture",
    description: "Atlanta's legendary Labor Day weekend convention spanning multiple downtown hotels. 80,000+ attendees, famous parade through downtown, 24-hour programming, and one of the best cosplay scenes in the world.",
    website: "https://www.dragoncon.org",
    highlights: ["Dragon Con Parade", "24-hour programming", "Cosplay", "Multiple hotel venues"],
  },
  {
    name: "HeroesCon",
    city: "Charlotte",
    state: "North Carolina",
    stateAbbr: "NC",
    dates: "June 12–14, 2026",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    tier: 2,
    type: "comic-con",
    description: "Founded in 1982, HeroesCon is a comics-first convention that honors the tradition and creativity at the heart of comic books. Legendary artist alley, massive back-issue dealers, original art, and creator signings. A must for serious comic collectors.",
    website: "https://www.heroesonline.com/heroescon",
    highlights: ["Comics-first focus", "Legendary Artist Alley", "Back-issue dealers", "Original art", "Creator signings"],
  },
  {
    name: "Awesome Con",
    city: "Washington",
    state: "District of Columbia",
    stateAbbr: "DC",
    dates: "March 13–15, 2026",
    startDate: "2026-03-13",
    endDate: "2026-03-15",
    tier: 2,
    type: "comic-con",
    description: "The nation's capital gets its own major convention at the Walter E. Washington Convention Center. Comics, cosplay, gaming, and celebrity guests in the heart of DC.",
    website: "https://www.awesome-con.com",
    highlights: ["Walter E. Washington Convention Center", "Celebrity guests", "Kids Day", "Cosplay"],
  },
  {
    name: "Planet Comicon",
    city: "Kansas City",
    state: "Missouri",
    stateAbbr: "MO",
    dates: "March 27–29, 2026",
    startDate: "2026-03-27",
    endDate: "2026-03-29",
    tier: 2,
    type: "comic-con",
    description: "The Midwest's largest multi-fandom pop culture convention. Three days of comics, cosplay, gaming, celebrity guests, and one of the best vendor halls in the region.",
    website: "https://www.planetcomicon.com",
    highlights: ["Midwest's largest", "Celebrity guests", "Vendor hall", "Cosplay contest"],
  },
  {
    name: "Fan Expo Cleveland",
    city: "Cleveland",
    state: "Ohio",
    stateAbbr: "OH",
    dates: "March 13–15, 2026",
    startDate: "2026-03-13",
    endDate: "2026-03-15",
    tier: 2,
    type: "pop-culture",
    description: "Part of the Fan Expo HQ circuit. Comics, sci-fi, horror, anime, and gaming converge in Cleveland for a weekend of celebrity guests, cosplay, and vendor shopping.",
    website: "https://fanexpohq.com/fanexpocleveland",
    highlights: ["Fan Expo circuit", "Celebrity guests", "Gaming tournaments"],
  },
  {
    name: "Baltimore Comic Con",
    city: "Baltimore",
    state: "Maryland",
    stateAbbr: "MD",
    dates: "September 25–27, 2026",
    startDate: "2026-09-25",
    endDate: "2026-09-27",
    tier: 2,
    type: "comic-con",
    description: "A true comics convention — focused on comic books, comic art, and the creators who make them. Known for its Harvey Awards ceremony and one of the best artist alleys on the East Coast.",
    website: "https://www.baltimorecomiccon.com",
    highlights: ["Harvey Awards", "Comics-focused", "Artist Alley", "Creator panels"],
  },
  {
    name: "Rose City Comic Con",
    city: "Portland",
    state: "Oregon",
    stateAbbr: "OR",
    dates: "September 11–13, 2026",
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    tier: 2,
    type: "comic-con",
    description: "Portland's biggest pop culture event. Strong indie comics presence, great cosplay community, and a welcoming atmosphere that reflects Portland's creative spirit.",
    website: "https://www.rosecitycomiccon.com",
    highlights: ["Indie comics", "Cosplay", "Portland vibes", "Creator-friendly"],
  },
  {
    name: "Florida Supercon",
    city: "Miami Beach",
    state: "Florida",
    stateAbbr: "FL",
    dates: "July 10–12, 2026",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    tier: 2,
    type: "comic-con",
    description: "South Florida's largest pop culture convention at the Miami Beach Convention Center. Comics, anime, gaming, cosplay, and celebrity guests in a tropical setting.",
    website: "https://www.floridasupercon.com",
    highlights: ["Miami Beach Convention Center", "Celebrity guests", "Cosplay", "Anime content"],
  },
  {
    name: "Motor City Comicon",
    city: "Novi",
    state: "Michigan",
    stateAbbr: "MI",
    dates: "May 15–17, 2026",
    startDate: "2026-05-15",
    endDate: "2026-05-17",
    tier: 2,
    type: "comic-con",
    description: "Michigan's longest-running comic convention. A true comic book show with massive dealer rooms, original art, and a strong focus on the medium itself.",
    website: "https://www.motorcitycomiccon.com",
    highlights: ["Longest-running in Michigan", "Dealer rooms", "Original art", "Creator signings"],
  },
  {
    name: "Fan Expo Boston",
    city: "Boston",
    state: "Massachusetts",
    stateAbbr: "MA",
    dates: "August 7–9, 2026",
    startDate: "2026-08-07",
    endDate: "2026-08-09",
    tier: 2,
    type: "pop-culture",
    description: "New England's biggest pop culture event. Part of the Fan Expo circuit with major celebrity guests, comics, cosplay, and gaming across a massive show floor.",
    website: "https://fanexpohq.com/fanexpoboston",
    highlights: ["Fan Expo circuit", "Celebrity guests", "New England's biggest"],
  },
  {
    name: "Fan Expo Chicago",
    city: "Chicago",
    state: "Illinois",
    stateAbbr: "IL",
    dates: "August 14–16, 2026",
    startDate: "2026-08-14",
    endDate: "2026-08-16",
    tier: 2,
    type: "pop-culture",
    description: "Chicago's summer pop culture convention. Part of the Fan Expo circuit with celebrity guests, comics, gaming, and cosplay.",
    website: "https://fanexpohq.com/fanexpochicago",
    highlights: ["Fan Expo circuit", "Summer timing", "Celebrity guests"],
  },
  {
    name: "Dallas Fan Expo",
    city: "Dallas",
    state: "Texas",
    stateAbbr: "TX",
    dates: "September 11–13, 2026",
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    tier: 2,
    type: "pop-culture",
    description: "Texas-sized pop culture event in the heart of Dallas. Major celebrity guests, massive vendor hall, and one of the biggest cons in the South.",
    website: "https://fanexpohq.com/fanexpodallas",
    highlights: ["Fan Expo circuit", "Texas-sized", "Celebrity guests"],
  },
  {
    name: "Fan Expo San Francisco",
    city: "San Francisco",
    state: "California",
    stateAbbr: "CA",
    dates: "November 27–29, 2026",
    startDate: "2026-11-27",
    endDate: "2026-11-29",
    tier: 2,
    type: "pop-culture",
    description: "The Bay Area's premier pop culture convention. Comics, gaming, cosplay, and celebrity guests in one of America's most iconic cities.",
    website: "https://fanexpohq.com/fanexposanfrancisco",
    highlights: ["Bay Area", "Fan Expo circuit", "Holiday weekend timing"],
  },
  {
    name: "FanX",
    city: "Salt Lake City",
    state: "Utah",
    stateAbbr: "UT",
    dates: "September 24–26, 2026",
    startDate: "2026-09-24",
    endDate: "2026-09-26",
    tier: 2,
    type: "pop-culture",
    description: "Salt Lake City's massive pop culture convention. 100,000+ attendees make it one of the biggest in the Mountain West. Celebrity guests, panels, cosplay, and a huge vendor floor.",
    website: "https://fanxsaltlake.com",
    highlights: ["100,000+ attendees", "Mountain West's biggest", "Celebrity guests"],
  },

  // ===== GALAXYCON CIRCUIT (Tier 2) =====
  {
    name: "GalaxyCon Richmond",
    city: "Richmond",
    state: "Virginia",
    stateAbbr: "VA",
    dates: "March 19–22, 2026",
    startDate: "2026-03-19",
    endDate: "2026-03-22",
    tier: 2,
    type: "pop-culture",
    description: "Part of the GalaxyCon traveling circuit. Comics, anime, gaming, celebrity guests, and cosplay in Virginia's capital city.",
    website: "https://galaxycon.com",
    highlights: ["GalaxyCon circuit", "Celebrity guests", "Cosplay"],
  },
  {
    name: "GalaxyCon Oklahoma City",
    city: "Oklahoma City",
    state: "Oklahoma",
    stateAbbr: "OK",
    dates: "May 22–24, 2026",
    startDate: "2026-05-22",
    endDate: "2026-05-24",
    tier: 2,
    type: "pop-culture",
    description: "GalaxyCon brings its traveling pop culture experience to Oklahoma City. Celebrity guests, comics, cosplay, and gaming.",
    website: "https://galaxycon.com",
    highlights: ["GalaxyCon circuit", "Celebrity guests"],
  },
  {
    name: "GalaxyCon Raleigh",
    city: "Raleigh",
    state: "North Carolina",
    stateAbbr: "NC",
    dates: "July 23–26, 2026",
    startDate: "2026-07-23",
    endDate: "2026-07-26",
    tier: 2,
    type: "pop-culture",
    description: "One of GalaxyCon's flagship events in the Research Triangle. 4 days of celebrity guests, comics, cosplay, and gaming.",
    website: "https://galaxycon.com",
    highlights: ["GalaxyCon flagship", "4-day event", "Celebrity guests"],
  },
  {
    name: "GalaxyCon San Jose",
    city: "San Jose",
    state: "California",
    stateAbbr: "CA",
    dates: "August 21–23, 2026",
    startDate: "2026-08-21",
    endDate: "2026-08-23",
    tier: 2,
    type: "pop-culture",
    description: "GalaxyCon's Bay Area stop. Silicon Valley meets pop culture with celebrity guests, comics, and cosplay.",
    website: "https://galaxycon.com",
    highlights: ["GalaxyCon circuit", "Bay Area", "Celebrity guests"],
  },
  {
    name: "GalaxyCon St. Louis",
    city: "St. Louis",
    state: "Missouri",
    stateAbbr: "MO",
    dates: "October 23–25, 2026",
    startDate: "2026-10-23",
    endDate: "2026-10-25",
    tier: 2,
    type: "pop-culture",
    description: "GalaxyCon's Midwest stop in the Gateway City. Celebrity guests, comics, cosplay, and gaming.",
    website: "https://galaxycon.com",
    highlights: ["GalaxyCon circuit", "Midwest", "Celebrity guests"],
  },
  {
    name: "GalaxyCon Milwaukee",
    city: "Milwaukee",
    state: "Wisconsin",
    stateAbbr: "WI",
    dates: "October 30–November 1, 2026",
    startDate: "2026-10-30",
    endDate: "2026-11-01",
    tier: 2,
    type: "pop-culture",
    description: "GalaxyCon's Halloween-weekend event in Milwaukee. Celebrity guests, comics, cosplay, and gaming with a spooky twist.",
    website: "https://galaxycon.com",
    highlights: ["GalaxyCon circuit", "Halloween weekend", "Celebrity guests"],
  },
  {
    name: "GalaxyCon Columbus",
    city: "Columbus",
    state: "Ohio",
    stateAbbr: "OH",
    dates: "December 4–6, 2026",
    startDate: "2026-12-04",
    endDate: "2026-12-06",
    tier: 2,
    type: "pop-culture",
    description: "GalaxyCon's holiday-season event in Columbus. Celebrity guests, comics, cosplay, and gaming to close out the year.",
    website: "https://galaxycon.com",
    highlights: ["GalaxyCon circuit", "Holiday season", "Celebrity guests"],
  },
  {
    name: "GalaxyCon New Orleans",
    city: "New Orleans",
    state: "Louisiana",
    stateAbbr: "LA",
    dates: "July 10–12, 2026",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    tier: 2,
    type: "pop-culture",
    description: "GalaxyCon brings its traveling pop culture experience to the Big Easy. Celebrity guests, comics, cosplay, and gaming in one of America's most unique cities.",
    website: "https://galaxycon.com",
    highlights: ["GalaxyCon circuit", "New Orleans", "Celebrity guests"],
  },

  // ===== TIER 3: STRONG REGIONAL / NICHE / GROWING =====
  {
    name: "DreamCon",
    city: "Houston",
    state: "Texas",
    stateAbbr: "TX",
    dates: "July 10–12, 2026",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    tier: 3,
    type: "pop-culture",
    description: "Houston's growing pop culture convention celebrating diversity in fandom. Comics, cosplay, gaming, and celebrity guests with a focus on inclusion and community.",
    highlights: ["Diversity-focused", "Growing event", "Community-driven"],
  },
  {
    name: "Garden State Comic Fest",
    city: "Vineland",
    state: "New Jersey",
    stateAbbr: "NJ",
    dates: "June 27–28, 2026",
    startDate: "2026-06-27",
    endDate: "2026-06-28",
    tier: 3,
    type: "comic-con",
    description: "New Jersey's vibrant comic fest transforms the arena into a marketplace where comics, cosplay, and collectibles collide. Expansive vendor hall, dedicated Artist Alley, celebrity guests, and family-friendly fun.",
    website: "https://www.gardenstatecomicfest.com",
    highlights: ["Vendor hall", "Artist Alley", "Celebrity guests", "Family-friendly"],
  },
  {
    name: "Big Lick Comic Con: NOVA",
    city: "Manassas",
    state: "Virginia",
    stateAbbr: "VA",
    dates: "May 30–31, 2026",
    startDate: "2026-05-30",
    endDate: "2026-05-31",
    tier: 3,
    type: "comic-con",
    description: "A lively, family-friendly pop culture convention in Northern Virginia celebrating comics, collectibles, gaming, cosplay, and beyond. Free parking, on-site dining, and a welcoming atmosphere.",
    website: "https://www.biglickcomiccon.com",
    highlights: ["Family-friendly", "Free parking", "Comics & collectibles", "Cosplay"],
  },
  {
    name: "Big Lick Comic Con: Roanoke",
    city: "Roanoke",
    state: "Virginia",
    stateAbbr: "VA",
    dates: "August 8–9, 2026",
    startDate: "2026-08-08",
    endDate: "2026-08-09",
    tier: 3,
    type: "comic-con",
    description: "Big Lick Comic Con returns to Roanoke with comics, pop culture, cosplay, creators, celebrity guests, and vendors. Comic dealers, back-issue specialists, and Artist Alley with local and national artists.",
    website: "https://www.biglickcomiccon.com",
    highlights: ["Comic dealers", "Back-issue specialists", "Artist Alley", "Celebrity guests"],
  },
  {
    name: "Tampa Bay Comic Convention",
    city: "Tampa",
    state: "Florida",
    stateAbbr: "FL",
    dates: "September 4–6, 2026",
    startDate: "2026-09-04",
    endDate: "2026-09-06",
    tier: 3,
    type: "comic-con",
    description: "Tampa Bay's own comic convention bringing together comics, collectibles, cosplay, and celebrity guests on Florida's Gulf Coast.",
    highlights: ["Gulf Coast", "Comics & collectibles", "Celebrity guests"],
  },
  {
    name: "Indiana Comic Convention",
    city: "Indianapolis",
    state: "Indiana",
    stateAbbr: "IN",
    dates: "June 5–7, 2026",
    startDate: "2026-06-05",
    endDate: "2026-06-07",
    tier: 3,
    type: "comic-con",
    description: "Indianapolis' premier comic convention. Comics, cosplay, gaming, and celebrity guests in the heart of the Midwest.",
    highlights: ["Indianapolis", "Comics & cosplay", "Celebrity guests"],
  },
  {
    name: "PAX East",
    city: "Boston",
    state: "Massachusetts",
    stateAbbr: "MA",
    dates: "March 26–29, 2026",
    startDate: "2026-03-26",
    endDate: "2026-03-29",
    tier: 2,
    type: "anime-gaming",
    description: "One of the biggest gaming conventions in the US. While gaming-focused, PAX East features a massive expo hall with collectibles, comics vendors, and pop culture merchandise alongside the latest in video games and tabletop gaming.",
    website: "https://east.paxsite.com",
    highlights: ["Gaming focus", "Expo hall", "Tabletop gaming", "Indie games"],
  },
  {
    name: "Long Beach Comic Con",
    city: "Long Beach",
    state: "California",
    stateAbbr: "CA",
    dates: "September 5–6, 2026",
    startDate: "2026-09-05",
    endDate: "2026-09-06",
    tier: 3,
    type: "comic-con",
    description: "Southern California's community-driven comic convention. Strong indie comics presence, artist alley, and a more intimate alternative to the mega-cons.",
    highlights: ["Indie comics", "Artist Alley", "Community-driven"],
  },
  {
    name: "Rhode Island Comic Con",
    city: "Providence",
    state: "Rhode Island",
    stateAbbr: "RI",
    dates: "November 6–8, 2026",
    startDate: "2026-11-06",
    endDate: "2026-11-08",
    tier: 3,
    type: "comic-con",
    description: "New England's fall comic convention. Celebrity guests, comics, cosplay, and a massive vendor hall in Providence.",
    website: "https://www.ricomiccon.com",
    highlights: ["New England", "Celebrity guests", "Fall timing"],
  },
  {
    name: "Twin Cities Con",
    city: "Minneapolis",
    state: "Minnesota",
    stateAbbr: "MN",
    dates: "November 20–22, 2026",
    startDate: "2026-11-20",
    endDate: "2026-11-22",
    tier: 3,
    type: "pop-culture",
    description: "Minnesota's own pop culture convention in the Twin Cities. Comics, cosplay, gaming, and celebrity guests. A great local option for Midwest collectors and fans.",
    highlights: ["Minnesota local", "Comics & cosplay", "Celebrity guests"],
  },
  {
    name: "The Uncanny Experience",
    city: "Minneapolis",
    state: "Minnesota",
    stateAbbr: "MN",
    dates: "September 12–13, 2026",
    startDate: "2026-09-12",
    endDate: "2026-09-13",
    tier: 3,
    type: "comic-con",
    description: "A unique comic convention experience in Minneapolis focused on comics, creators, and the art form itself.",
    highlights: ["Comics-focused", "Creator-driven", "Minneapolis"],
  },
  {
    name: "Fan Expo Denver",
    city: "Denver",
    state: "Colorado",
    stateAbbr: "CO",
    dates: "May 28–31, 2026",
    startDate: "2026-05-28",
    endDate: "2026-05-31",
    tier: 3,
    type: "pop-culture",
    description: "Denver's biggest pop culture event. Part of the Fan Expo circuit with celebrity guests, comics, cosplay, and gaming in the Mile High City.",
    website: "https://fanexpohq.com/fanexpodenver",
    highlights: ["Fan Expo circuit", "Mile High City", "Celebrity guests"],
  },
  {
    name: "Fan Expo Philadelphia",
    city: "Philadelphia",
    state: "Pennsylvania",
    stateAbbr: "PA",
    dates: "May 29–31, 2026",
    startDate: "2026-05-29",
    endDate: "2026-05-31",
    tier: 3,
    type: "pop-culture",
    description: "Philadelphia's pop culture convention. Part of the Fan Expo circuit with celebrity guests, comics, cosplay, and gaming in the City of Brotherly Love.",
    website: "https://fanexpohq.com/fanexpophiladelphia",
    highlights: ["Fan Expo circuit", "Philadelphia", "Celebrity guests"],
  },
  {
    name: "Colorado Springs Comic Con",
    city: "Colorado Springs",
    state: "Colorado",
    stateAbbr: "CO",
    dates: "August 21–23, 2026",
    startDate: "2026-08-21",
    endDate: "2026-08-23",
    tier: 3,
    type: "comic-con",
    description: "Colorado Springs' own comic convention. Comics, cosplay, gaming, and collectibles at the base of the Rocky Mountains.",
    highlights: ["Colorado Springs", "Comics & collectibles"],
  },
  {
    name: "TerrifiCon",
    city: "Uncasville",
    state: "Connecticut",
    stateAbbr: "CT",
    dates: "August 7–9, 2026",
    startDate: "2026-08-07",
    endDate: "2026-08-09",
    tier: 3,
    type: "comic-con",
    description: "Connecticut's premier comic convention at Mohegan Sun. Comics, celebrity guests, cosplay, and a unique casino resort setting.",
    highlights: ["Mohegan Sun", "Casino resort setting", "Celebrity guests"],
  },
  {
    name: "Spacecon San Antonio",
    city: "San Antonio",
    state: "Texas",
    stateAbbr: "TX",
    dates: "June 12–14, 2026",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    tier: 3,
    type: "pop-culture",
    description: "San Antonio's pop culture convention. Comics, sci-fi, gaming, and cosplay in the heart of Texas.",
    highlights: ["San Antonio", "Comics & sci-fi"],
  },
  {
    name: "3 Rivers Comicon",
    city: "Pittsburgh",
    state: "Pennsylvania",
    stateAbbr: "PA",
    dates: "June 6–7, 2026",
    startDate: "2026-06-06",
    endDate: "2026-06-07",
    tier: 3,
    type: "comic-con",
    description: "Pittsburgh's comic convention celebrating comics, creators, and the Steel City's growing pop culture scene.",
    highlights: ["Pittsburgh", "Comics-focused", "Creator-friendly"],
  },
  {
    name: "MagicCon Las Vegas",
    city: "Las Vegas",
    state: "Nevada",
    stateAbbr: "NV",
    dates: "May 1–3, 2026",
    startDate: "2026-05-01",
    endDate: "2026-05-03",
    tier: 3,
    type: "pop-culture",
    description: "A premium pop culture experience in Las Vegas. Celebrity guests, panels, and exclusive events in the entertainment capital of the world.",
    highlights: ["Las Vegas", "Premium experience", "Celebrity guests"],
  },
  {
    name: "Pop Con Indy",
    city: "Indianapolis",
    state: "Indiana",
    stateAbbr: "IN",
    dates: "May 8–10, 2026",
    startDate: "2026-05-08",
    endDate: "2026-05-10",
    tier: 3,
    type: "pop-culture",
    description: "Indianapolis' pop culture convention. Comics, gaming, cosplay, and celebrity guests in the Crossroads of America.",
    highlights: ["Indianapolis", "Pop culture", "Celebrity guests"],
  },
  {
    name: "Des Moines Con",
    city: "Des Moines",
    state: "Iowa",
    stateAbbr: "IA",
    dates: "May 29–31, 2026",
    startDate: "2026-05-29",
    endDate: "2026-05-31",
    tier: 3,
    type: "comic-con",
    description: "Iowa's comic convention bringing comics, cosplay, and pop culture to the heartland.",
    highlights: ["Iowa", "Comics & cosplay"],
  },
  {
    name: "MagicCon Atlanta",
    city: "Atlanta",
    state: "Georgia",
    stateAbbr: "GA",
    dates: "November 13–15, 2026",
    startDate: "2026-11-13",
    endDate: "2026-11-15",
    tier: 3,
    type: "pop-culture",
    description: "A premium pop culture experience in Atlanta. Celebrity guests, panels, and exclusive events.",
    highlights: ["Atlanta", "Premium experience", "Celebrity guests"],
  },

  // ===== TIER 4: LOCAL / RECURRING / SMALLER =====
  {
    name: "Little Giant Comics Old School Comic Show",
    city: "Concord",
    state: "New Hampshire",
    stateAbbr: "NH",
    dates: "April 11, 2026",
    startDate: "2026-04-11",
    endDate: "2026-04-11",
    tier: 4,
    type: "comic-con",
    description: "A one-day event focused entirely on comic books, creators, and original art. No movie stars, no pop culture distractions — just comics. Meet creators like Mark Bagley, David Michelinie, Dan Jurgens. CGC grading on-site.",
    highlights: ["Comics-only focus", "CGC on-site", "Creator signings", "Back-issue dealers"],
  },
  {
    name: "Super Jersey Comic Expo",
    city: "Jackson",
    state: "New Jersey",
    stateAbbr: "NJ",
    dates: "April 18–19, 2026",
    startDate: "2026-04-18",
    endDate: "2026-04-19",
    tier: 4,
    type: "comic-con",
    description: "New Jersey's community-oriented comic expo. Vendors, artists, trading bins, and a spirited celebration of comic fandom.",
    highlights: ["Community-oriented", "Vendors & artists", "Trading bins"],
  },
  {
    name: "Super Jersey Summer Spectacular",
    city: "Hillsborough",
    state: "New Jersey",
    stateAbbr: "NJ",
    dates: "August 29, 2026",
    startDate: "2026-08-29",
    endDate: "2026-08-29",
    tier: 4,
    type: "comic-con",
    description: "A condensed one-day celebration of comic fandom featuring vendors, artists, trading bins, and guests. Born from the resilient spirit of the Super Jersey brand.",
    highlights: ["One-day event", "Vendors & artists", "Trading bins"],
  },
  {
    name: "Shoff Promotions Comic Book & Card Show",
    city: "Annandale",
    state: "Virginia",
    stateAbbr: "VA",
    dates: "Monthly (Mar 29, Apr 26, May 24, Jun 28)",
    startDate: "2026-03-29",
    endDate: "2026-06-28",
    tier: 4,
    type: "card-show",
    recurring: true,
    description: "Recurring monthly comic book and non-sports card show at the Annandale Fire Station. Great for finding back issues, trading cards, and connecting with local dealers.",
    highlights: ["Monthly recurring", "Comic books & cards", "Local dealers"],
  },
  {
    name: "Frederick Maryland Comic Con",
    city: "Frederick",
    state: "Maryland",
    stateAbbr: "MD",
    dates: "July 19 & November 15, 2026",
    startDate: "2026-07-19",
    endDate: "2026-11-15",
    tier: 4,
    type: "comic-con",
    description: "Frederick's local comic convention at the Clarion Inn Frederick Event Center. Comics, collectibles, and local dealers.",
    highlights: ["Local show", "Comics & collectibles"],
  },
  {
    name: "SC Comic Con",
    city: "Greenville",
    state: "South Carolina",
    stateAbbr: "SC",
    dates: "April 11–12, 2026",
    startDate: "2026-04-11",
    endDate: "2026-04-12",
    tier: 4,
    type: "comic-con",
    description: "South Carolina's comic convention in Greenville. Comics, cosplay, and collectibles in the Upstate.",
    highlights: ["South Carolina", "Comics & cosplay"],
  },
  {
    name: "Annapolis Comic-Con",
    city: "Annapolis",
    state: "Maryland",
    stateAbbr: "MD",
    dates: "April 18, 2026",
    startDate: "2026-04-18",
    endDate: "2026-04-18",
    tier: 4,
    type: "comic-con",
    description: "A one-day comic convention in Maryland's capital city. Comics, creators, and collectibles.",
    highlights: ["One-day event", "Annapolis"],
  },
  {
    name: "Lexington Comic and Toy Convention",
    city: "Lexington",
    state: "Kentucky",
    stateAbbr: "KY",
    dates: "March 26–29, 2026",
    startDate: "2026-03-26",
    endDate: "2026-03-29",
    tier: 4,
    type: "comic-con",
    description: "Lexington's comic and toy convention. Comics, toys, collectibles, and pop culture in the Bluegrass State.",
    highlights: ["Comics & toys", "Kentucky"],
  },
  {
    name: "Hollywood Comic Con",
    city: "Grantville",
    state: "Pennsylvania",
    stateAbbr: "PA",
    dates: "March 27–28, 2026",
    startDate: "2026-03-27",
    endDate: "2026-03-28",
    tier: 4,
    type: "comic-con",
    description: "Pennsylvania's Hollywood-themed comic convention. Comics, celebrity guests, and collectibles.",
    highlights: ["Pennsylvania", "Celebrity guests"],
  },
  {
    name: "Collective Con",
    city: "Jacksonville",
    state: "Florida",
    stateAbbr: "FL",
    dates: "March 27–29, 2026",
    startDate: "2026-03-27",
    endDate: "2026-03-29",
    tier: 4,
    type: "comic-con",
    description: "Jacksonville's pop culture convention. Comics, cosplay, gaming, and celebrity guests in Northeast Florida.",
    highlights: ["Jacksonville", "Comics & cosplay"],
  },
  {
    name: "Tupelo Con",
    city: "Tupelo",
    state: "Mississippi",
    stateAbbr: "MS",
    dates: "April 4–5, 2026",
    startDate: "2026-04-04",
    endDate: "2026-04-05",
    tier: 4,
    type: "comic-con",
    description: "Mississippi's comic convention in the birthplace of Elvis. Comics, cosplay, and collectibles.",
    highlights: ["Mississippi", "Tupelo"],
  },
  {
    name: "CoastCon",
    city: "Biloxi",
    state: "Mississippi",
    stateAbbr: "MS",
    dates: "March 6–8, 2026",
    startDate: "2026-03-06",
    endDate: "2026-03-08",
    tier: 4,
    type: "pop-culture",
    description: "One of the oldest continuously running conventions on the Gulf Coast. Sci-fi, fantasy, comics, and gaming in Biloxi.",
    highlights: ["One of the oldest", "Gulf Coast", "Sci-fi & fantasy"],
  },
  {
    name: "MidSouthCon",
    city: "Memphis",
    state: "Tennessee",
    stateAbbr: "TN",
    dates: "March 20–22, 2026",
    startDate: "2026-03-20",
    endDate: "2026-03-22",
    tier: 4,
    type: "pop-culture",
    description: "Memphis' long-running sci-fi and fantasy convention. Comics, gaming, cosplay, and a welcoming community atmosphere.",
    highlights: ["Memphis", "Long-running", "Sci-fi & fantasy"],
  },
  {
    name: "Kanpai!Con",
    city: "Omaha",
    state: "Nebraska",
    stateAbbr: "NE",
    dates: "April 3–5, 2026",
    startDate: "2026-04-03",
    endDate: "2026-04-05",
    tier: 4,
    type: "anime-gaming",
    description: "Omaha's anime and pop culture convention. Anime, manga, gaming, cosplay, and Japanese culture.",
    highlights: ["Anime focus", "Omaha", "Japanese culture"],
  },
  {
    name: "iMagicon",
    city: "Minot",
    state: "North Dakota",
    stateAbbr: "ND",
    dates: "April 24–26, 2026",
    startDate: "2026-04-24",
    endDate: "2026-04-26",
    tier: 4,
    type: "pop-culture",
    description: "North Dakota's pop culture convention in Minot. Comics, gaming, cosplay, and community fun.",
    highlights: ["North Dakota", "Community-driven"],
  },
  {
    name: "Causacon",
    city: "Beckley",
    state: "West Virginia",
    stateAbbr: "WV",
    dates: "May 1–3, 2026",
    startDate: "2026-05-01",
    endDate: "2026-05-03",
    tier: 4,
    type: "pop-culture",
    description: "West Virginia's pop culture convention in Beckley. Comics, gaming, cosplay, and a charitable focus.",
    highlights: ["West Virginia", "Charitable focus"],
  },
  {
    name: "AniMinneapolis",
    city: "Minneapolis",
    state: "Minnesota",
    stateAbbr: "MN",
    dates: "May 8–10, 2026",
    startDate: "2026-05-08",
    endDate: "2026-05-10",
    tier: 4,
    type: "anime-gaming",
    description: "Minneapolis' anime convention. Anime, manga, cosplay, gaming, and Japanese pop culture in the Twin Cities.",
    highlights: ["Anime focus", "Minneapolis", "Japanese culture"],
  },
  {
    name: "Gem State Comic Con",
    city: "Garden City",
    state: "Idaho",
    stateAbbr: "ID",
    dates: "May 15–17, 2026",
    startDate: "2026-05-15",
    endDate: "2026-05-17",
    tier: 4,
    type: "comic-con",
    description: "Idaho's comic convention. Comics, cosplay, and collectibles in the Gem State.",
    highlights: ["Idaho", "Comics & collectibles"],
  },
  {
    name: "AtomaCon",
    city: "North Charleston",
    state: "South Carolina",
    stateAbbr: "SC",
    dates: "May 16–17, 2026",
    startDate: "2026-05-16",
    endDate: "2026-05-17",
    tier: 4,
    type: "pop-culture",
    description: "South Carolina's pop culture convention in North Charleston. Comics, sci-fi, gaming, and cosplay.",
    highlights: ["South Carolina", "Sci-fi & comics"],
  },
  {
    name: "Tidewater Comicon",
    city: "Virginia Beach",
    state: "Virginia",
    stateAbbr: "VA",
    dates: "May 16–17, 2026",
    startDate: "2026-05-16",
    endDate: "2026-05-17",
    tier: 4,
    type: "comic-con",
    description: "Virginia Beach's comic convention. Comics, cosplay, and collectibles on the coast.",
    highlights: ["Virginia Beach", "Coastal setting"],
  },
  {
    name: "MomoCon",
    city: "Atlanta",
    state: "Georgia",
    stateAbbr: "GA",
    dates: "May 21–24, 2026",
    startDate: "2026-05-21",
    endDate: "2026-05-24",
    tier: 3,
    type: "anime-gaming",
    description: "Atlanta's massive anime, gaming, and comics convention. 35,000+ attendees, free admission for some events, and a vibrant community atmosphere.",
    highlights: ["35,000+ attendees", "Anime & gaming", "Free events"],
  },
  {
    name: "Tremendicon",
    city: "Springfield",
    state: "Missouri",
    stateAbbr: "MO",
    dates: "May 29–31, 2026",
    startDate: "2026-05-29",
    endDate: "2026-05-31",
    tier: 4,
    type: "comic-con",
    description: "Springfield, Missouri's comic convention. Comics, cosplay, and pop culture in the Ozarks.",
    highlights: ["Springfield", "Ozarks"],
  },
  {
    name: "Black Hills Con",
    city: "Rapid City",
    state: "South Dakota",
    stateAbbr: "SD",
    dates: "June 12–14, 2026",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    tier: 4,
    type: "pop-culture",
    description: "South Dakota's pop culture convention near Mount Rushmore. Comics, gaming, cosplay, and a unique Black Hills setting.",
    highlights: ["South Dakota", "Near Mount Rushmore", "Unique setting"],
  },
  {
    name: "JoeFest",
    city: "Augusta",
    state: "Georgia",
    stateAbbr: "GA",
    dates: "June 26–28, 2026",
    startDate: "2026-06-26",
    endDate: "2026-06-28",
    tier: 4,
    type: "collectibles",
    description: "Augusta's collectibles festival. G.I. Joe, action figures, comics, and vintage toys.",
    highlights: ["G.I. Joe focus", "Action figures", "Vintage toys"],
  },
  {
    name: "Capital City Comic Con",
    city: "Lansing",
    state: "Michigan",
    stateAbbr: "MI",
    dates: "July 10–12, 2026",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    tier: 4,
    type: "comic-con",
    description: "Lansing, Michigan's comic convention. Comics, cosplay, and collectibles in the state capital.",
    highlights: ["Lansing", "State capital"],
  },
  {
    name: "FarleyCon Comic Book Expo",
    city: "East Ridge",
    state: "Tennessee",
    stateAbbr: "TN",
    dates: "August 1–2, 2026",
    startDate: "2026-08-01",
    endDate: "2026-08-02",
    tier: 4,
    type: "comic-con",
    description: "Tennessee's comic book expo near Chattanooga. Comics, creators, and collectibles.",
    highlights: ["Near Chattanooga", "Comics-focused"],
  },
  {
    name: "PulpFest",
    city: "Mars",
    state: "Pennsylvania",
    stateAbbr: "PA",
    dates: "July 30–August 2, 2026",
    startDate: "2026-07-30",
    endDate: "2026-08-02",
    tier: 4,
    type: "collectibles",
    description: "A unique convention celebrating pulp magazines, vintage paperbacks, and the golden age of adventure fiction. A must for vintage collectors.",
    highlights: ["Pulp magazines", "Vintage collectibles", "Golden age"],
  },
  {
    name: "PropCon Daytona Beach",
    city: "Daytona Beach",
    state: "Florida",
    stateAbbr: "FL",
    dates: "August 15–16, 2026",
    startDate: "2026-08-15",
    endDate: "2026-08-16",
    tier: 4,
    type: "collectibles",
    description: "Daytona Beach's prop and collectibles convention. Movie props, replicas, comics, and pop culture memorabilia.",
    highlights: ["Movie props", "Replicas", "Daytona Beach"],
  },
  {
    name: "D23",
    city: "Anaheim",
    state: "California",
    stateAbbr: "CA",
    dates: "August 14–16, 2026",
    startDate: "2026-08-14",
    endDate: "2026-08-16",
    tier: 2,
    type: "pop-culture",
    description: "Disney's official fan event. Major Marvel, Star Wars, Pixar, and Disney announcements. Exclusive collectibles and once-in-a-lifetime experiences for Disney fans.",
    website: "https://d23.com",
    highlights: ["Disney official", "Marvel announcements", "Star Wars", "Exclusive collectibles"],
  },
  {
    name: "Anime Expo",
    city: "Los Angeles",
    state: "California",
    stateAbbr: "CA",
    dates: "July 2–5, 2026",
    startDate: "2026-07-02",
    endDate: "2026-07-05",
    tier: 2,
    type: "anime-gaming",
    description: "The largest anime convention in North America. 100,000+ attendees, Japanese pop culture, manga, cosplay, and a massive exhibit hall with collectibles and merchandise.",
    website: "https://www.anime-expo.org",
    highlights: ["Largest anime con in NA", "100,000+ attendees", "Japanese culture", "Exhibit hall"],
  },
  {
    name: "Anime NYC",
    city: "New York City",
    state: "New York",
    stateAbbr: "NY",
    dates: "August 20–23, 2026",
    startDate: "2026-08-20",
    endDate: "2026-08-23",
    tier: 3,
    type: "anime-gaming",
    description: "New York City's premier anime convention. Anime, manga, cosplay, and Japanese pop culture at the Javits Center.",
    highlights: ["Javits Center", "Anime & manga", "NYC"],
  },
  {
    name: "North Shore Collectors Fest",
    city: "Danvers",
    state: "Massachusetts",
    stateAbbr: "MA",
    dates: "April 18–19, 2026",
    startDate: "2026-04-18",
    endDate: "2026-04-19",
    tier: 4,
    type: "collectibles",
    description: "A collectors-focused fest on Boston's North Shore. Trading cards, comics, toys, and vintage collectibles.",
    highlights: ["Collectors-focused", "Trading cards", "North Shore"],
  },
  {
    name: "Kingston Independent Comic Expo",
    city: "Kingston",
    state: "New York",
    stateAbbr: "NY",
    dates: "April 18, 2026",
    startDate: "2026-04-18",
    endDate: "2026-04-18",
    tier: 4,
    type: "comic-con",
    description: "An indie comics expo in Kingston, NY. Independent creators, small press publishers, and original art.",
    highlights: ["Indie comics", "Small press", "Original art"],
  },
  {
    name: "Kids Con New England",
    city: "Portland",
    state: "Maine",
    stateAbbr: "ME",
    dates: "April 12, 2026",
    startDate: "2026-04-12",
    endDate: "2026-04-12",
    tier: 4,
    type: "comic-con",
    description: "A family-friendly comic convention designed specifically for kids and families. Comics, cosplay, and activities in Portland, Maine.",
    highlights: ["Family-friendly", "Kid-focused", "Portland, ME"],
  },
  {
    name: "Kawaii Kon",
    city: "Honolulu",
    state: "Hawaii",
    stateAbbr: "HI",
    dates: "April 24–26, 2026",
    startDate: "2026-04-24",
    endDate: "2026-04-26",
    tier: 4,
    type: "anime-gaming",
    description: "Hawaii's anime convention. Anime, manga, cosplay, and Japanese pop culture in paradise.",
    highlights: ["Hawaii", "Anime focus", "Tropical setting"],
  },
  {
    name: "Fan Fusion Expo",
    city: "West Springfield",
    state: "Massachusetts",
    stateAbbr: "MA",
    dates: "July 25–26, 2026",
    startDate: "2026-07-25",
    endDate: "2026-07-26",
    tier: 4,
    type: "pop-culture",
    description: "Western Massachusetts' pop culture expo. Comics, cosplay, gaming, and celebrity guests.",
    highlights: ["Western Mass", "Pop culture"],
  },
];

// Helper functions
export function getComicConsByState(stateAbbr: string): ComicConEvent[] {
  return comicConEvents.filter(e => e.stateAbbr === stateAbbr).sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function getComicConsByMonth(month: number): ComicConEvent[] {
  return comicConEvents.filter(e => {
    const m = parseInt(e.startDate.split("-")[1]);
    return m === month;
  }).sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function getComicConsByTier(tier: 1 | 2 | 3 | 4): ComicConEvent[] {
  return comicConEvents.filter(e => e.tier === tier).sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function getComicConsByType(type: ComicConEvent["type"]): ComicConEvent[] {
  return comicConEvents.filter(e => e.type === type).sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function searchComicCons(query: string): ComicConEvent[] {
  const q = query.toLowerCase();
  return comicConEvents.filter(e =>
    e.name.toLowerCase().includes(q) ||
    e.city.toLowerCase().includes(q) ||
    e.state.toLowerCase().includes(q) ||
    e.stateAbbr.toLowerCase() === q ||
    e.description.toLowerCase().includes(q)
  ).sort((a, b) => a.startDate.localeCompare(b.startDate));
}

export function getUniqueStates(): string[] {
  return Array.from(new Set(comicConEvents.map(e => e.stateAbbr))).sort();
}

export function getUniqueTypes(): ComicConEvent["type"][] {
  return Array.from(new Set(comicConEvents.map(e => e.type)));
}

export const TIER_LABELS: Record<number, { label: string; emoji: string; color: string }> = {
  1: { label: "National", emoji: "🏆", color: "text-yellow-400" },
  2: { label: "Major Regional", emoji: "🥈", color: "text-gray-300" },
  3: { label: "Regional", emoji: "🥉", color: "text-amber-600" },
  4: { label: "Local", emoji: "📍", color: "text-emerald-400" },
};

export const TYPE_LABELS: Record<string, { label: string; color: string }> = {
  "comic-con": { label: "Comic Con", color: "bg-blue-500/20 text-blue-300 border-blue-500/30" },
  "collectibles": { label: "Collectibles", color: "bg-amber-500/20 text-amber-300 border-amber-500/30" },
  "anime-gaming": { label: "Anime & Gaming", color: "bg-purple-500/20 text-purple-300 border-purple-500/30" },
  "pop-culture": { label: "Pop Culture", color: "bg-pink-500/20 text-pink-300 border-pink-500/30" },
  "card-show": { label: "Card Show", color: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30" },
};
