CREATE TABLE `articles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`slug` varchar(500) NOT NULL,
	`excerpt` text,
	`contentMarkdown` text NOT NULL,
	`featuredImageUrl` text,
	`category` enum('movie_news','show_news','casting','card_market','release_dates','rumors','analysis') NOT NULL DEFAULT 'movie_news',
	`tags` json,
	`cardMarketImpact` text,
	`relatedCharacters` json,
	`sources` json,
	`isFeatured` boolean NOT NULL DEFAULT false,
	`isPublished` boolean NOT NULL DEFAULT false,
	`authorName` varchar(255) DEFAULT 'NLF Team',
	`publishedAt` bigint,
	`metaDescription` varchar(320),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `articles_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `top5_buzz_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rank` int NOT NULL,
	`title` varchar(500) NOT NULL,
	`character` varchar(255) NOT NULL,
	`tagline` varchar(500) NOT NULL,
	`backstory` text NOT NULL,
	`cardImage` text NOT NULL,
	`frontImage` text,
	`backImage` text,
	`frameTemplate` varchar(100) DEFAULT 'marvel_mint_gold',
	`cardLabel` varchar(255) NOT NULL,
	`cardLink` varchar(500) NOT NULL,
	`sources` json NOT NULL,
	`heatLevel` enum('blazing','hot','rising') NOT NULL DEFAULT 'rising',
	`category` varchar(100) NOT NULL DEFAULT 'Movie',
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `top5_buzz_items_id` PRIMARY KEY(`id`)
);
