CREATE TABLE `show_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`showName` varchar(255) NOT NULL,
	`promoterName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`website` varchar(500),
	`venue` varchar(255),
	`address` varchar(500),
	`city` varchar(100) NOT NULL,
	`state` varchar(2) NOT NULL,
	`zipCode` varchar(10),
	`startDate` bigint NOT NULL,
	`endDate` bigint NOT NULL,
	`hours` varchar(255),
	`tableCount` int,
	`admission` varchar(100),
	`description` text,
	`isRecurring` boolean NOT NULL DEFAULT false,
	`recurrenceNote` varchar(255),
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`submittedByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `show_submissions_id` PRIMARY KEY(`id`)
);
