CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`slug` varchar(500) NOT NULL,
	`excerpt` text,
	`contentMarkdown` text NOT NULL,
	`featuredImageUrl` text,
	`blog_category` enum('market_trends','character_spotlight','grading_guide','set_breakdown','investment_strategy','collecting_tips','nlf_news','behind_the_scenes','card_history') NOT NULL DEFAULT 'market_trends',
	`tags` json,
	`isAiGenerated` boolean NOT NULL DEFAULT false,
	`aiPrompt` text,
	`isFeatured` boolean NOT NULL DEFAULT false,
	`isPublished` boolean NOT NULL DEFAULT false,
	`authorName` varchar(255) DEFAULT 'NLF Team',
	`publishedAt` bigint,
	`scheduledAt` bigint,
	`metaDescription` varchar(320),
	`focusKeyword` varchar(255),
	`internalLinks` json,
	`readTimeMinutes` int DEFAULT 5,
	`viewCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
