CREATE TABLE `slab_pack_cards` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slabPackId` int NOT NULL,
	`cardName` varchar(255) NOT NULL,
	`cardSet` varchar(255),
	`cardYear` varchar(10),
	`cardNumber` varchar(50),
	`parallel` varchar(150),
	`serialNumber` varchar(50),
	`gradingCompany` varchar(20),
	`grade` varchar(30),
	`gradeNumeric` decimal(3,1),
	`tier` enum('grail','chase','lineup') NOT NULL DEFAULT 'lineup',
	`estimatedValueCents` int,
	`frontImageUrl` text,
	`backImageUrl` text,
	`status` enum('available','claimed','removed') NOT NULL DEFAULT 'available',
	`pullMethod` enum('digital','in_person'),
	`pulledBy` varchar(255),
	`orderId` int,
	`pulledAt` timestamp,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `slab_pack_cards_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `slab_packs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`imageUrl` text,
	`priceCents` int NOT NULL,
	`slabsPerPack` int NOT NULL DEFAULT 1,
	`totalPacks` int,
	`packsSold` int NOT NULL DEFAULT 0,
	`tier` enum('silver','gold','diamond','infinity') NOT NULL DEFAULT 'silver',
	`status` enum('draft','coming_soon','active','soldout','archived') NOT NULL DEFAULT 'draft',
	`launchDate` bigint,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `slab_packs_id` PRIMARY KEY(`id`),
	CONSTRAINT `slab_packs_slug_unique` UNIQUE(`slug`)
);
