CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(500) NOT NULL,
	`eventType` varchar(50) NOT NULL DEFAULT 'card-show',
	`tier` int,
	`dateDisplay` varchar(255) NOT NULL,
	`startDate` varchar(10) NOT NULL,
	`endDate` varchar(10) NOT NULL,
	`month` int NOT NULL,
	`venue` varchar(500),
	`address` varchar(500),
	`city` varchar(255) NOT NULL,
	`state` varchar(2) NOT NULL,
	`stateName` varchar(100),
	`hours` varchar(500),
	`tableCount` int,
	`admission` varchar(255),
	`isFree` boolean,
	`email` varchar(320),
	`phone` varchar(50),
	`website` varchar(500),
	`description` text,
	`highlights` text,
	`featured` boolean DEFAULT false,
	`recurring` boolean DEFAULT false,
	`source` varchar(100),
	`sourceId` varchar(255),
	`sourceUrl` varchar(500),
	`eventStatus` enum('approved','pending','rejected') NOT NULL DEFAULT 'approved',
	`lastScrapedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `events_id` PRIMARY KEY(`id`)
);
