CREATE TABLE `card_shows` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(500) NOT NULL,
	`slug` varchar(500) NOT NULL,
	`dateDisplay` varchar(100) NOT NULL,
	`startDate` varchar(10) NOT NULL,
	`endDate` varchar(10) NOT NULL,
	`month` int NOT NULL,
	`venue` varchar(500),
	`address` varchar(500),
	`city` varchar(100) NOT NULL,
	`state` varchar(5) NOT NULL,
	`stateName` varchar(100) NOT NULL,
	`hours` varchar(255),
	`tableCount` int,
	`admission` varchar(255),
	`isFree` boolean DEFAULT false,
	`email` varchar(320),
	`phone` varchar(50),
	`website` varchar(500),
	`featured` boolean DEFAULT false,
	`show_status` enum('upcoming','past','cancelled') NOT NULL DEFAULT 'upcoming',
	`source` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `card_shows_id` PRIMARY KEY(`id`),
	CONSTRAINT `card_shows_slug_unique` UNIQUE(`slug`)
);
