CREATE TABLE `mcu_media` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`mediaType` enum('movie','series') NOT NULL,
	`phase` int,
	`releaseOrder` int,
	`releaseDate` varchar(50),
	`director` varchar(255),
	`cast` text,
	`tagline` varchar(500),
	`description` text,
	`imageUrl` text,
	`youtubeTrailerId` varchar(20),
	`budgetMillions` int,
	`worldwideGrossMillions` int,
	`domesticGrossMillions` int,
	`openingWeekendMillions` int,
	`episodeCount` int,
	`seasonCount` int,
	`platform` varchar(100),
	`rtCriticsScore` int,
	`rtAudienceScore` int,
	`verdict` enum('hit','miss','mixed') DEFAULT 'hit',
	`cardMarketContent` text,
	`keyCards` text,
	`content` text,
	`metaDescription` varchar(320),
	`keywords` text,
	`relatedCharacters` json,
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`isFeatured` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mcu_media_id` PRIMARY KEY(`id`),
	CONSTRAINT `mcu_media_slug_unique` UNIQUE(`slug`)
);
